# Generated by Django 3.2.7 on 2021-09-12 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_food_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='date',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='reservate',
        ),
        migrations.AlterField(
            model_name='menu',
            name='about',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='menu',
            name='rest_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_list', to='online_food_api.restaurant'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='online_food_api.customer'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='online_food_api.order'),
        ),
        migrations.CreateModel(
            name='Reating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cust', to='online_food_api.customer')),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ord', to='online_food_api.menu')),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cat_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='online_food_api.category'),
            preserve_default=False,
        ),
    ]
